### ISSUE TITLE
¿Podfile?

### ISSUE THREAD

**Issue by josepfm** [FernandoBorgesPaul/MiTodoApp#1]
Hola Fernando, encantado.

Iba a echarle un ojo a esta primera versión de tu app y he visto que falta el archivo de configuración de los pods, es posible?

**Comment by FernandoBorgesPaul** [comment]
Hola José! 

Gusto en conocerte igual! Agradezco mucho tu observación. En un momento subiré el archivo de configuración. 

Muchas gracias!
